flyway:
    enabled: false
jwt:
    expiration: 604800
    secret: _@POE&L3tF?65O9j4z&L5!nU2B!eT65_
paginacao:
    qtd_por_pagina: 25
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
    jpa:
        hibernate:
            ddl-auto: create
    profiles:
        active: hom
